name: First
on: 
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    workflow_dispatch:
jobs:
    deneme:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Hello World Script
              run: |
                echo "Hello, World!"
                printenv
                   
              
        